apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName:  build-container-pipeline-
spec:
  pipelineRef:
    name:  hello-goodbye-pipeline
  workspaces:
    - name: build-workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 50Mi
